//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id_orase { get; set; }
        public int Id_consultanti { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual Consultanti Consultanti { get; set; }
    }
}
